name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    # job-level working-directory: cliappを使っていないのは、uv pytestなどを実行するときに実行想定のディレクトリと異なってしまうため
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v2

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('cliapp/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies (uv)
        working-directory: cliapp
        run: |
          uv venv
          uv pip install -e .[dev]

      - name: Lint - isort (check)
        working-directory: cliapp
        run: uv run isort --check --diff .

      - name: Lint - black (check)
        working-directory: cliapp
        run: uv run black --check .

      - name: Type check - mypy
        working-directory: cliapp
        run: uv run mypy .

      - name: Run unit tests
        working-directory: cliapp
        run: uv run pytest -q